In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import glob
import os
print("done")

done


In [2]:
calibration_imgs = glob.glob("camera_cal/calibration*.jpg")

In [3]:
def calibrate_cam(calibration_imgs):
    img_pts = []
    obj_pts = []

    for img_name in calibration_imgs:
        img = mpimg.imread(img_name)
        gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
        #print(img_name)
        
        for board_size in [(9,6),(9,5),(8,6),(8,5)]:
            #print("---try:", board_size)
            ret, corners = cv2.findChessboardCorners(gray_img, board_size, None)
            print(corners)
            if ret:
                #print("board_size:", board_size)
                obj_p = np.zeros((board_size[0]*board_size[1], 3),np.float32)
                obj_p[:,:2] = np.mgrid[0:board_size[0],0:board_size[1]].T.reshape(-1,2)
                img_pts.append(corners)
                obj_pts.append(obj_p)
                img = cv2.drawChessboardCorners(img, board_size, corners, ret)
                cv2.imwrite("./camera_cal_output/output_" + img_name[11:] , cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
                #print(img_name, " completed")
                break
    ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(obj_pts, img_pts, gray_img.shape[::-1], None, None)
    return (ret, mtx, dist)

In [4]:
ret, mtx, dist = calibrate_cam(calibration_imgs)
print("ret: ", ret)
for img_name in calibration_imgs:
    img = mpimg.imread(img_name)
    dst = cv2.undistort(img, mtx, dist, None, mtx)
    cv2.imwrite("./camera_cal_output/undistorted_" + img_name[11:] , cv2.cvtColor(dst, cv2.COLOR_BGR2RGB))

[[[  509.     24. ]]

 [[  501.    137.5]]

 [[  499.    260.5]]

 [[  377.    255.5]]

 [[  246.5   250.5]]

 [[  374.5   386.5]]

 [[  244.5   386. ]]

 [[  497.    386.5]]

 [[  495.    512. ]]

 [[  375.5   516. ]]

 [[  247.    521.5]]

 [[  381.    642.5]]

 [[  252.    654.5]]

 [[  499.    633.5]]

 [[  608.5   504.5]]

 [[  608.5   621.5]]

 [[  611.5   387. ]]

 [[  715.5   387. ]]

 [[  714.5   500. ]]

 [[  710.    612.5]]

 [[  804.5   495. ]]

 [[  803.5   603. ]]

 [[  807.    387. ]]

 [[  890.    387. ]]

 [[  888.    490.5]]

 [[  885.    591.5]]

 [[  962.5   485. ]]

 [[  961.    582. ]]

 [[  965.    387.5]]

 [[ 1034.    388. ]]

 [[ 1031.5   481.5]]

 [[ 1029.    574. ]]

 [[  890.    283.5]]

 [[  965.    288.5]]

 [[ 1033.5   293.5]]

 [[  964.    191.5]]

 [[ 1031.5   201.5]]

 [[  889.     81. ]]

 [[  963.     96. ]]

 [[  889.    181.5]]

 [[ 1030.    110. ]]

 [[  807.     66. ]]

 [[  807.5   170. ]]

 [[  807.    277.5]]

 [[  715.5    49.5]]

 [[  716. 

None
[[[  136.7457428     98.02098083]]

 [[  253.75596619    90.30776215]]

 [[  377.65280151    84.52696228]]

 [[  507.55761719    80.32173157]]

 [[  638.96813965    78.58662415]]

 [[  770.03924561    79.13419342]]

 [[  898.67156982    82.42144775]]

 [[ 1021.82653809    87.11566162]]

 [[ 1137.53295898    92.94205475]]

 [[  133.88349915   222.09674072]]

 [[  251.90190125   217.20980835]]

 [[  375.81835938   212.80905151]]

 [[  506.69094849   209.87051392]]

 [[  639.80462646   208.41624451]]

 [[  771.96734619   208.63671875]]

 [[  901.49737549   210.10264587]]

 [[ 1024.81958008   212.66563416]]

 [[ 1141.84057617   215.94309998]]

 [[  133.92164612   348.15899658]]

 [[  251.49960327   345.95849609]]

 [[  376.6836853    343.95632935]]

 [[  507.77355957   342.44818115]]

 [[  640.75811768   341.28112793]]

 [[  773.10552979   340.36599731]]

 [[  902.70404053   340.16159058]]

 [[ 1026.48693848   340.18127441]]

 [[ 1144.22253418   340.43432617]]

 [[  138.30949402   475

[[[ 402.62612915  298.50134277]]

 [[ 468.99658203  298.15881348]]

 [[ 535.74658203  298.45605469]]

 [[ 603.02929688  298.81674194]]

 [[ 669.99902344  299.49121094]]

 [[ 736.47668457  300.44012451]]

 [[ 802.44287109  301.17895508]]

 [[ 866.64257812  302.36968994]]

 [[ 930.04022217  303.91830444]]

 [[ 404.70306396  363.32315063]]

 [[ 470.07015991  363.47879028]]

 [[ 535.87731934  364.21691895]]

 [[ 602.63110352  364.72470093]]

 [[ 668.67340088  365.19317627]]

 [[ 734.4052124   365.42147827]]

 [[ 799.31549072  365.48010254]]

 [[ 862.99993896  366.03970337]]

 [[ 925.43664551  366.94403076]]

 [[ 407.04330444  426.75372314]]

 [[ 471.35089111  427.71652222]]

 [[ 536.43383789  428.51043701]]

 [[ 602.40423584  428.94622803]]

 [[ 667.63555908  429.4230957 ]]

 [[ 732.41021729  428.79833984]]

 [[ 796.79443359  428.76678467]]

 [[ 858.99682617  428.37127686]]

 [[ 920.94561768  428.52655029]]

 [[ 409.47476196  489.38153076]]

 [[ 473.02127075  490.07849121]]

 [[ 537.115905

[[[ 622.58782959  147.0605011 ]]

 [[ 661.10717773  162.30953979]]

 [[ 697.171875    177.32293701]]

 [[ 731.4342041   191.53643799]]

 [[ 763.58044434  205.23521423]]

 [[ 793.97033691  218.34291077]]

 [[ 822.23474121  230.58575439]]

 [[ 849.57879639  242.72918701]]

 [[ 874.94433594  253.93637085]]

 [[ 619.67712402  195.31033325]]

 [[ 658.80511475  209.68055725]]

 [[ 696.32061768  223.31027222]]

 [[ 731.3692627   236.34934998]]

 [[ 763.24615479  249.07751465]]

 [[ 793.24523926  261.38589478]]

 [[ 821.71472168  273.08724976]]

 [[ 849.02600098  283.84960938]]

 [[ 875.22705078  294.35696411]]

 [[ 618.07739258  244.71977234]]

 [[ 657.83972168  257.97540283]]

 [[ 694.78619385  270.69213867]]

 [[ 730.32147217  282.52490234]]

 [[ 762.53045654  294.46026611]]

 [[ 792.22320557  305.56552124]]

 [[ 821.44061279  315.80917358]]

 [[ 849.40893555  325.71697998]]

 [[ 876.28430176  335.0960083 ]]

 [[ 614.5536499   296.57077026]]

 [[ 654.62469482  308.61502075]]

 [[ 692.539245